version: '3'
services:
  traefik:
    container_name: traefik
    image: traefik:2.6
    ports:
      - "80:80"
      - "443:443"
      - "8183:8080"  # Dashboard port (optional)
    volumes:
      - /opt/appdata/traefik/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock:ro # Ensure direct socket access (if needed)
    networks:
      - proxy # rename this to your custom docker network
    labels:
      # Labels for Traefik Dashboard
      traefik.http.routers.api.rule: Host(`traefik.${DOMAIN_NAME}`)
      traefik.http.routers.api.entryPoints: https
      traefik.http.routers.api.service: api@internal
      traefik.enable: true
    environment:
      DOCKER_HOST: tcp://dockersocket:2375  # Ensure Traefik points to the docker socket proxy
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    restart: unless-stopped
    depends_on:
      - dockersocket

  dockersocket:
    container_name: dockersocket
    image: tecnativa/docker-socket-proxy
    ports:
      - "2375:2375"  # Expose docker socket proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    environment:
      CONTAINERS: 1
      POST: 0
    privileged: true
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
